version: "3"
name: time_tracker_prod
services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: time_tracker_prod_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create && bin/rails db:migrate && bin/rails db:seed && bin/rails server -b '0.0.0.0' -e production"
  db:
    image: "postgres:15.3-bookworm"
    container_name: time_tracker_prod_pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql@15/data
volumes:
  data:
